.PHONY: clean
.PHONY: init

init:
	mkdir -p logs
	mkdir -p derived_data
	mkdir -p figures
	mkdir -p versioned_reports

clean:
	rm -rf derived_data
	rm -rf figures
	rm -rf logs
	rm -rf versioned_reports
	mkdir -p derived_data
	mkdir -p figures
	mkdir -p logs
	mkdir -p versioned_reports


clean-report.pdf: deps ...
	rm -f current-commit.Rmd && touch current-commit.Rmd
	R -r "rmarkdown::render(\"report.Rmd\", output_format=\"pdf_document\", output_file=\"\clean-report.pdf")"
	mkdir -p versioned_reports/
	cp clean-report.pdf versioned_reports/`git log -1 | head -n1 | cut -d' ' -f2`.pdf



